name: very_cloudy
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.13.5
  - selenium=4.12.0
  - lxml=4.9.3
  - seaborn=0.12.2
  - openpyxl=3.1.2
  - pytest=7.4.2
  - plotly=5.18.0
  - box2d-py=2.3 
  - ffmpeg=6.1
  - graphviz  
  - python-graphviz
  - ipython=8.17
  - ipywidgets=8.1
  - joblib=1.3
  - jupyterlab=4.0
  - matplotlib=3.8
  - nbdime=3.2
  - nltk=3.8
  - numexpr=2.8
  - numpy=1.26
  - pandas=2.1
  - pillow=10.1
  - pip
  - pip:
    - webdriver-manager==4.0.0
    - pdfplumber==0.10.2
    - rich==13.5.2
    - PyMuPDF==1.23.3
    - netCDF4==1.7.3
  - pydot=1.4
  - python=3.10
  - requests=2.31
  - scikit-learn=1.3
  - scipy=1.11
  - statsmodels=0.14
  - tqdm=4.66
  - wheel
  - widgetsnbextension=4.0
  - xlsxwriter=3.2.0
  - spacy=3.7.2
  - geotext=0.4.0
  - geopy=2.4.1
  - pycountry=24.6.1
  - ipykernel=6.29.5
  - aiohttp=3.9.1
  - exifread=3.0.0
  - python-dotenv>=1.0.0