"""
Entry point for Task C — cloud type and subtype extraction.

Usage:
    python scripts/main_cloudtype.py
"""

from verycloudy.config import (
    FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER, FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER_TESTSET, 
    FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER_TYPE, FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER_TYPE_TESTSET
)

from cloudtype import run

run(FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER_TESTSET, FILEPATH_CLOUDS_WITH_DATE_LOC_WEATHER_TYPE_TESTSET)
